apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-app-deploy
  namespace: bggns
  labels:
    app: bgg-app-deploy
spec:
  replicas: 3
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  selector:
    matchLabels:
      name: bgg-app-pod
  template:
    metadata:
      name: bgg-app-pod
      labels:
        name: bgg-app-pod
    spec:
      containers:
      - name: bgg-app-container
        image: stackupiss/bgg-backend:v2
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: BGG_DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: database_username
        - name: BGG_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: database_host
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database_password
---

apiVersion: v1
kind: Service
metadata:
  name: bgg-app-svc
  namespace: bggns
spec:
    type: LoadBalancer
    selector:
        name: bgg-app-pod
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 31111